version: "3.6"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: magical_password
      POSTGRES_DB: conferencedb
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data/ # persist data even if container shuts down

volumes:
  postgres: